### ISSUE TITLE
Incomplete List of Misinformation Websites

### ISSUE THREAD

**Issue by sehgalvibhor** [eric-zeng/conpro-bad-ads-data#1]
Hi,

Thanks for sharing this amazing dataset and your research work. I was going through the paper and noticed that in the paper you have mentioned that you used a list of 1158 misinformation websites but the dataset has only 608 websites. I was wondering, where can I get the complete list?

Thanks!

**Comment by eric-zeng** [comment]
Hi Vibhor,

There are fewer sites in the final dataset than our input list because some of the sites either did not have any ads, did not have ads visible to our crawler, or were no longer active at the time of the crawl.

If you'd like the list of misinformation sites we used, you can get them from the sources that we compiled them from:
- https://www.cjr.org/fake-beta (previously at https://web.archive.org/web/20190501173436/https://www.poynter.org/ifcn/unreliable-news-index/)
- https://mediabiasfactcheck.com/fake-news/
- http://www.propornot.com/p/home.html
- https://www.alexa.com/topsites/category/Top/News/Alternative

We haven't released them as a full, aggregated list, because each list has different methodologies for defining and labeling what is mis/disinformation or "fake news" - so rather than using our list as a blanket definition for "misinformation", we suggest you look at these sources directly and decide which best fit your goals!
